### PR TITLE
Fix: namespace issues with `hk_accidents`

### LINKED ISSUE #15: hk_accidents namespace not found
Just installed the latest version of the package (0893dcaaed17500331d497b5d012cac05c8df5ce) for testing. Yet, looks like the `hk_accidents` namespace is not correctly exported?

``` r
library(hkdatasets)

hkdatasets::hk_accidents
#> Error: 'hk_accidents' is not an exported object from 'namespace:hkdatasets'
```

<sup>Created on 2021-08-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I could get the dataset when using `:::`.

Screenshot 2021-08-16 at 02 49 38

And other datasets could also be found with `::`.

Screenshot 2021-08-16 at 02 51 57

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.1.0 (2021-05-18)
#>  os       macOS Big Sur 10.16         
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Asia/Hong_Kong              
#>  date     2021-08-16                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date       lib
#>  cli           2.5.0   2021-04-26 [1]
#>  digest        0.6.27  2020-10-24 [1]
#>  evaluate      0.14    2019-05-28 [1]
#>  fs            1.5.0   2020-07-31 [1]
#>  glue          1.4.2   2020-08-27 [1]
#>  highr         0.9     2021-04-16 [1]
#>  hkdatasets  * 0.0.5   2021-08-15 [1]
#>  htmltools     0.5.1.1 2021-01-22 [1]
#>  knitr         1.33    2021-04-24 [1]
#>  magrittr      2.0.1   2020-11-17 [1]
#>  reprex        2.0.0   2021-04-02 [1]
#>  rlang         0.4.11  2021-04-30 [1]
#>  rmarkdown     2.9     2021-06-15 [1]
#>  rstudioapi    0.13    2020-11-12 [1]
#>  sessioninfo   1.1.1   2018-11-05 [1]
#>  stringi       1.6.2   2021-05-17 [1]
#>  stringr       1.4.0   2019-02-10 [1]
#>  withr         2.4.2   2021-04-18 [1]
#>  xfun          0.24    2021-06-15 [1]
#>  yaml          2.2.1   2020-02-01 [1]
#>  source                                              
#>  CRAN (R 4.1.0)                                      
#>  CRAN (R 4.1.0)                                      
#>  CRAN (R 4.1.0)                                      
#>  CRAN (R 4.1.0)                                      
#>  CRAN (R 4.1.0)                                      
#>  CRAN (R 4.1.0)                                      
#>  Github (Hong-Kong-Districts-Info/hkdatasets@0893dca)
#>  CRAN (R 4.1.0)                                      
#>  CRAN (R 4.1.0)                                      
#>  CRAN (R 4.1.0)                                      
#>  CRAN (R 4.1.0)                                      
#>  CRAN (R 4.1.0)                                      
#>  CRAN (R 4.1.0)                                      
#>  CRAN (R 4.1.0)                                      
#>  CRAN (R 4.1.0)                                      
#>  CRAN (R 4.1.0)                                      
#>  CRAN (R 4.1.0)                                      
#>  CRAN (R 4.1.0)                                      
#>  CRAN (R 4.1.0)                                      
#>  CRAN (R 4.1.0)                                      
#> 
#> [1] /Library/Frameworks/R.framework/Versions/4.1/Resources/library
```

</details>

### PR DESCRIPTION
**Pull request by martinctc**
# Summary
This branch resolves the loading error with `hk_accidents` as mentioned in #15. 

To resolve this error, a new implementation is introduced, where `download_data()` is a function that downloads and reads in the data into R using `fst::read_fst()`.  The datasets are stored in the `fst` format on GitHub for fast loading and high compression. 

# Changes
The changes made in this PR are:
1. Removed the defunct method of loading `hk_accidents` as this causes issues with CRAN R-CMD-checks. 
2. Added new `fst` files to GitHub (committed directly to `master` branch, separately). These files are stored in `data-ready`, which is ignored by R via `.Rbuildignore`. 
3. Added function `download_data()`. 

# New implementation
You can download and return a dataset with the following code:
```R
download_data(dataset = "hk_accidents")
download_data(dataset = "hk_casualties")
download_data(dataset = "hk_vehicles")
```
The files are downloaded to a temporary directory, and the `download_data()` function returns a data frame directly.

***

# Check
- [x] The R CMD checks pass.

***

## Note
This fixes #15.

### CODE REVIEW

File: R/download_data.R [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+#' ```
+#' 
+#' @export   
+download_data <- function(dataset = NULL){
+  
+  if(is.null(dataset)){
+    
+    stop("please provide the name of the dataset to pull.")
+    
+  }
```
Comment (KHwong12) [inline R/download_data.R]: Would it be better to impose a stricter check of the dataset name? If the user typed the dataset name wrong, the `cannot open URL 'https://github.com/Hong-Kong-Districts-Info/hkdatasets/raw/master/data-ready/SOME-RANDOM-CHARS.fst'` error message may be hard to understand.

```suggestion
AVAILABLE_DATASETS = c("hk_accidents", "hk_casualties", "hk_vehicles")

if (!(dataset %in% AVAILABLE_DATASETS)) {
  stop(
    paste0("Please provide the name of the dataset to pull.\n",
           "Datasets currently available: ",
           # Convert column vector to text first
           paste0(AVAILABLE_DATASETS, collapse = ", ")
           )
  )
}
```

**Review by KHwong12 — COMMENTED** [review]
Thanks for this new implementation (and introducing fst format to me)! Only have one concern about the download link.

**Comment by KHwong12** [comment]
One additional question - are data types preserved when converted to **fst** format?

I compared the native dataset and the fst file of **hk_accidents** and do not see observable differences. Just want to ensure things will not go wrong for other datasets.

<details>
 <summary>Native dataset</summary>

```
str(hk_accidents)
'data.frame':	95821 obs. of  32 variables:
 $ Date_Time                   : POSIXct, format: "2014-01-01 02:17:00" "2014-01-01 06:17:00" "2014-01-01 07:38:00" "2014-01-01 05:22:00" ...
 $ OBJECTID                    : num  1 2 3 4 5 6 7 8 9 10 ...
 $ Year                        : num  2014 2014 2014 2014 2014 ...
 $ Serial_No_                  : num  1 2 3 4 5 6 7 8 9 10 ...
 $ Severity                    : chr  "Serious" "Slight" "Slight" "Slight" ...
 $ District_Council_District   : chr  "E" "CW" "YTM" "N" ...
 $ Hit_and_Run                 : logi  FALSE FALSE FALSE TRUE FALSE FALSE ...
 $ Weather                     : chr  "Clear" "Clear" "Clear" "Dull" ...
 $ Rain                        : chr  "Not raining" "Not raining" "Not raining" "Not raining" ...
 $ Natural_Light               : chr  "Daylight" "Dawn/Dusk" "Daylight" "Dark" ...
 $ Junction_Control            : chr  "Not junction" "Traffic signal" "Not junction" "Traffic signal" ...
 $ Vehicle_Movements           : chr  "One moving vehicle" "One moving vehicle" "One moving vehicle" "Two moving vehicles - from opposite direction" ...
 $ Type_of_Collision           : chr  "Vehicle collision with Object" "Vehicle collision with Nothing" "Vehicle collision with Object" "Vehicle collision with Vehicle" ...
 $ No_of_Vehicles_Involved     : num  1 1 1 3 1 1 2 2 1 1 ...
 $ No_of_Casualties_Injured    : num  1 1 2 2 1 1 1 6 1 2 ...
 $ Grid_E                      : num  840782 832909 835270 830780 837229 ...
 $ Grid_N                      : num  816576 816551 817969 840400 825912 ...
 $ latitude                    : num  22.3 22.3 22.3 22.5 22.4 ...
 $ longitude                   : num  114 114 114 114 114 ...
 $ Within_70m                  : logi  FALSE TRUE FALSE TRUE FALSE FALSE ...
 $ Precise_Location            : chr  "Near Lamppost 28647 Island Eastern Corridor" "Outside No. 137 Des Voeux Road West" "China Hong Kong City No. 33 - 33 Canton Road YT Kowloon Tower 3, Podium (No road closure)" "Near Lamppost AD8473 Po Shek Wu Road Sheung Shui New Territories æ°•äŠ°å¶Ÿæ–·è‘‡æ±™ç¼D8473" ...
 $ Accident                    : logi  FALSE TRUE FALSE TRUE FALSE FALSE ...
 $ Junction_Type               : chr  NA "Cross roads" NA "Cross roads" ...
 $ Crossing_Control            : chr  "No crossing control" "On a crossing control" "No crossing control" "On a crossing control" ...
 $ Crossing_Type               : chr  NA NA NA NA ...
 $ Street_Name                 : chr  "ISLAND EASTERN CORRIDOR" "DES VOEUX ROAD WEST" "CANTON ROAD" "PO SHEK WU ROAD" ...
 $ Road_Type                   : chr  "One way" "Two way" "One way" "More than 2 carriageways" ...
 $ Cycle_Type                  : chr  "Others" "Others" "Others" "Others" ...
 $ Type_of_Collision_with_cycle: chr  "Vehicle collision with Object" "Vehicle collision with Nothing" "Vehicle collision with Object" "Vehicle collision with Vehicle" ...
 $ Structure_Type              : chr  "At grade road" "At grade road" "At grade road" "At grade road" ...
 $ Road_Hierarchy              : chr  "Expressway" "Main Road" "Secondary Road" "Main Road" ...
 $ Road_Ownership              : chr  "Public Road" "Public Road" "Public Road" "Public Road" ...
```

</details>


<details>
<summary>fst file</summary>

```
str(hk_accidents_fst_down)
'data.frame':	95821 obs. of  32 variables:
 $ Date_Time                   : POSIXct, format: "2014-01-01 02:17:00" "2014-01-01 06:17:00" "2014-01-01 07:38:00" "2014-01-01 05:22:00" ...
 $ OBJECTID                    : num  1 2 3 4 5 6 7 8 9 10 ...
 $ Year                        : num  2014 2014 2014 2014 2014 ...
 $ Serial_No_                  : num  1 2 3 4 5 6 7 8 9 10 ...
 $ Severity                    : chr  "Serious" "Slight" "Slight" "Slight" ...
 $ District_Council_District   : chr  "E" "CW" "YTM" "N" ...
 $ Hit_and_Run                 : logi  FALSE FALSE FALSE TRUE FALSE FALSE ...
 $ Weather                     : chr  "Clear" "Clear" "Clear" "Dull" ...
 $ Rain                        : chr  "Not raining" "Not raining" "Not raining" "Not raining" ...
 $ Natural_Light               : chr  "Daylight" "Dawn/Dusk" "Daylight" "Dark" ...
 $ Junction_Control            : chr  "Not junction" "Traffic signal" "Not junction" "Traffic signal" ...
 $ Vehicle_Movements           : chr  "One moving vehicle" "One moving vehicle" "One moving vehicle" "Two moving vehicles - from opposite direction" ...
 $ Type_of_Collision           : chr  "Vehicle collision with Object" "Vehicle collision with Nothing" "Vehicle collision with Object" "Vehicle collision with Vehicle" ...
 $ No_of_Vehicles_Involved     : num  1 1 1 3 1 1 2 2 1 1 ...
 $ No_of_Casualties_Injured    : num  1 1 2 2 1 1 1 6 1 2 ...
 $ Grid_E                      : num  840782 832909 835270 830780 837229 ...
 $ Grid_N                      : num  816576 816551 817969 840400 825912 ...
 $ latitude                    : num  22.3 22.3 22.3 22.5 22.4 ...
 $ longitude                   : num  114 114 114 114 114 ...
 $ Within_70m                  : logi  FALSE TRUE FALSE TRUE FALSE FALSE ...
 $ Precise_Location            : chr  "Near Lamppost 28647 Island Eastern Corridor" "Outside No. 137 Des Voeux Road West" "China Hong Kong City No. 33 - 33 Canton Road YT Kowloon Tower 3, Podium (No road closure)" "Near Lamppost AD8473 Po Shek Wu Road Sheung Shui New Territories æ°•äŠ°å¶Ÿæ–·è‘‡æ±™ç¼D8473" ...
 $ Accident                    : logi  FALSE TRUE FALSE TRUE FALSE FALSE ...
 $ Junction_Type               : chr  NA "Cross roads" NA "Cross roads" ...
 $ Crossing_Control            : chr  "No crossing control" "On a crossing control" "No crossing control" "On a crossing control" ...
 $ Crossing_Type               : chr  NA NA NA NA ...
 $ Street_Name                 : chr  "ISLAND EASTERN CORRIDOR" "DES VOEUX ROAD WEST" "CANTON ROAD" "PO SHEK WU ROAD" ...
 $ Road_Type                   : chr  "One way" "Two way" "One way" "More than 2 carriageways" ...
 $ Cycle_Type                  : chr  "Others" "Others" "Others" "Others" ...
 $ Type_of_Collision_with_cycle: chr  "Vehicle collision with Object" "Vehicle collision with Nothing" "Vehicle collision with Object" "Vehicle collision with Vehicle" ...
 $ Structure_Type              : chr  "At grade road" "At grade road" "At grade road" "At grade road" ...
 $ Road_Hierarchy              : chr  "Expressway" "Main Road" "Secondary Road" "Main Road" ...
 $ Road_Ownership              : chr  "Public Road" "Public Road" "Public Road" "Public Road" ...
```

</details>

File: R/download_data.R (hunk 1 above)
Comment (martinctc) [reply R/download_data.R]: That's a great suggestion. I'll add checks for the `dataset` argument input. Did this work for you locally? I like `fst` for its fast loading speed, so hopefully this will work as quite a scalable solution in the long term.

**Comment by martinctc** [comment]
> One additional question - are data types preserved when converted to **fst** format?
> 
> I compared the native dataset and the fst file of **hk_accidents** and do not see observable differences. Just want to ensure things will not go wrong for other datasets.
> 
> Native dataset
> fst file

As far as I'm aware all the main types like string, numeric, factors, and dates are preserved in `fst`. Unless we start doing trickier things like list-columns, we should be fine!

File: R/download_data.R (hunk 1 above)
Comment (KHwong12) [reply R/download_data.R]: Yep I ran the download and load fst data script in my local machine and it works well.

**Comment by KHwong12** [comment]
> > One additional question - are data types preserved when converted to **fst** format?
> > I compared the native dataset and the fst file of **hk_accidents** and do not see observable differences. Just want to ensure things will not go wrong for other datasets.
> > Native dataset
> > fst file
> 
> As far as I'm aware all the main types like string, numeric, factors, and dates are preserved in `fst`. Unless we start doing trickier things like list-columns, we should be fine!

Great. And probably we will not do list-columns as the dataset should be kept as simple as possible.

File: R/download_data.R (hunk 1 above)
Comment (martinctc) [reply R/download_data.R]: Fantastic. I've now added some notes on `NEWS.md` and `README`, but this should be ready to merge to main and push to CRAN once ready.
